name: Determine version

on:
  push:
    branches:
      - main

jobs:
  determine-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.semver.outputs.version }}
          name: ${{ steps.semver.outputs.version }}
          body: Changelog content
          token: ${{ github.token }}
          draft: false
          makeLatest: true
